@startmindmap microservices

*[#Orange] Микросервисы - элементы компонуемой архитектуры
**[#lightblue] Применение SOLID принципов к микросервисам
*** Single responsibility — принцип единственной ответственности
*** Open-closed — принцип открытости / закрытости
*** Liskov substitution — принцип подстановки Барбары Лисков
*** Interface segregation — принцип разделения 
*** Dependency inversion — принцип инверсии зависимостей
**[#lightblue] Применение CI/CD
*** Автоматизированные тесты как код
**** Unit
**** Интеграционные
*** Контейнеризация
*** Полная автоматизация сборок и релизов
*** Применение MD разметки для ReleaseNotes, ChangeLogs
**[#lightblue] Architecture as code
*** PlantUML
*** Применение MD разметки для ADR
*** Хранение ADR в репозиториях с кодом
**[#lightblue] Применение лучших практик и паттернов
*** Domain Driven Design
*** Сага
**** Хореография
**** Оркестрация
**** Сценарии компенсации
*** CQRS
*** DLQ паттерн при обработке сообщений
*** Идемпотентность запросов и обработки событий
'left side
**[#lightgreen] Быстрый time to market
**[#lightgreen] Гибкие требования к стеку и квалификации разработчиков
**[#lightgreen] Простота и быстрое время погружения новых участников команд в проект
**[#lightgreen] Простота развертывания и изменений
**[#lightgreen] Взаимозаменяемость в понимании Composable architecture
**[#lightgreen] Низкая связанность
@endmindmap